canonical/bundle-kubeflow

README.md, bundle.yaml
TensorFlow Serving requires being passed in a model to enter the active state, and `juju-wait` will currently block until TensorFlow Serving has entered the active state. Removing TensorFlow Serving from this bundle in favor of running it independently with a model specified.
=> Remove TensorFlow Serving from bundle

bundle.yaml
Instead of configuring Ambassador directly, we can add Annotations to each relevant Service.
Requires that we first successfully push each charm to the new `kubeflow-charmers` namespace.
=> Adding service annotations for Ambassador

bundle.yaml
Juju now supports Kubernetes annotations defined in pod-set-spec, which means we don't have to define it in the bundle.
=> Remove Ambassador annotations from bundle

scripts/deploy-microk8s.sh
Otherwise Bash interprets them as normal backticks that exec their contents.
=> Escape backtick characters in deploy-microk8s.sh

scripts/deploy-aws.sh
There are multiple models in play when the call is made, and we need to specify which one we want.
=> Adding model name to juju status call

overlays/jupyterhub-local-storage.yml
Lets user mount local paths into Jupyter Notebook instances
=> Add overlay for using local storage in Jupyterhub

bundle.yaml
@johnsca, @wallyworld: This is what I've got going to solve https://github.com/juju/charm-tools/issues/513, along with https://github.com/knkski/rust-libjuju. Should probably get everyone on board before merging this, so bikeshed away.
=> Bundle source paths

storage/is-default.yaml
For setting the juju operator storage class to be non-default, as otherwise it doesn't get metadata annotations that crash jupyter-web.
=> Add default storage class patch file

bundle.yaml
Remove unnecessary `kubeflow-` prefix, and copy mariadb to our own namespace
=> Correct charm names in bundle.yaml

.travis.yml
Juju 2.6 is out, and we can now run CI properly with stable
=> Disallow Travis CI failures for Juju stable

charms/jupyterhub/reactive/jupyterhub.py
Newer versions of kubernetes shuffled imports around, which broke kubespawner.
=> Lock kubernetes pip dependency for JupyterHub

overlays/cdk.yml
All of the Docker images take a fair amount of room, and disk space is cheap, so specify 100GB disks for the worker nodes.
=> Bump up storage for CDK deployments

scripts/deploy-microk8s
On slower machines, enabling multiple services at once can cause issues due to one service, i.e. DNS, not being booted up fully by the time the other service gets booted up.
=> Handling microk8s service startup race condition

charms/modeldb-store/config.yaml
It expects there to be at least one element in the list
=> Add noop modeldb-store bucket name

bundle.yaml, charms/mariadb/config.yaml, charms/mariadb/reactive/mariadb.py, charms/modeldb-backend/config.yaml, charms/modeldb-backend/layer.yaml, charms/modeldb-backend/metadata.yaml, charms/modeldb-backend/reactive/modeldb_backend.py, charms/modeldb-store/layer.yaml, charms/modeldb-store/metadata.yaml, charms/modeldb-store/reactive/modeldb_store.py
Moves modeldb-backend configuration to Python code, and fixes mysql charm to allow modeldb-backend to get connection data in configuration from relation data. Also updates modeldb-store to provide http relation.
=> Update ModelDB charm configurations

scripts/common.py, scripts/deploy-cdk, scripts/deploy-microk8s
Handles a snap binary of name `foo.bar` by only checking for the existence of `bar`, in case the user has it installed via a method other than snap, and allows specifying a snap package name to recommend installing instead of parsing the binary name.
=> Improve requires syntax in deploy scripts

.travis.yml
For easier debugging purposes when something goes wrong
=> Dump logs of failed instances in Travis CI

charms/pipelines-persistence/reactive/pipelines_persistence.py
Persistence was looking at itself and not Pipelines API
=> Fix Pipelines API name in Pipelines Persistence

.travis.yml, scripts/deploy-cdk, scripts/deploy-microk8s, scripts/manage-cdk
Allows printing out of info about deployed infrastructure whenever needed, instead of only after successful deploy.
=> Add info subcommand to deploy scripts

charms/minio/metadata.yaml
So that users won't lose data when tearing down the charm
=> Add storage to minio charm

charms/minio/metadata.yaml
It's very needy and doesn't like 1G space available.
=> Bump up minio charm's minimum storage size

tests/utils.py
`check_output` for `subprocess.run` was added in 3.7, and the default 18.04 image only has 3.6.
=> Make tests Python 3.6 compatible

overlays/cdk.yml, scripts/deploy-cdk, storage/aws-ebs.yml, storage/is-default.yml
If we manually create a StorageClass before Juju imports a cloud, Juju will use that one instead of creating its own to back the storage pools that it creates for itself. That then lets us specify the binding mode for the storage class, and support multi-az deployments with WaitForFirstConsumer.
Juju bug link: https://bugs.launchpad.net/juju/+bug/1839861
=> Work around Juju #1839861

charms/argo-controller/reactive/argo_controller.py, charms/jupyter-controller/reactive/jupyter_controller.py, charms/pipelines-persistence/reactive/pipelines_persistence.py, charms/pipelines-scheduledworkflow/reactive/pipelines_scheduledworkflow.py, charms/pytorch-operator/reactive/pytorch_operator.py, charms/tf-job-operator/reactive/tf_job_operator.py
Juju fixed a bug where omitting a service frontend wasn't allowed, so we can now drop the service frontends and dummy ports.
=> Omit service frontends / dummy ports on charms that don't need them

README.md
So that the links will work on jaas.ai.
Fixes #83
=> Use full URLs in README links

charms/katib-manager/reactive/katib_manager.py, charms/mariadb/reactive/mariadb.py, charms/modeldb-backend/reactive/modeldb_backend.py, charms/pipelines-api/reactive/pipelines_api.py
`mysql.connected` is racy and doesn't guarantee that connection information is available, but `mysql.available` does.
=> Correct usage of mysql interface flags

overlays/cdk-gpu.yml
Instead of deploying a total of 1 workers and setting all to be GPU instances, deploy the normal number of workers, and set 1 to be deployed to a GPU instance.
=> Deploy specific kubernetes worker to gpu instance in overlay

charms/argo-controller/config.yaml, overlays/cdk-kubeflow.yml, scripts/deploy-cdk
Since both CDK and Microk8s need it, let's just default to it and allow someone that needs the docker executor to override that.
=> Switch Argo runtime executor default to kubelet

charms/argo-controller/config.yaml, charms/argo-controller/reactive/argo_controller.py
Microk8s recently hardened security, and this breaks Argo, since it's a self-signed certificate.
=> Add Argo config option for skipping Kubelet TLS verification

tests/dump-pipeline-logs.sh
In case a pod has sidecars, we want to dump those logs as well.
=> Dump logs for each container in each pipeline pod

scripts/cli.py
`subprocess.run(..., capture_output=True)` was introduced in Python 3.7
=> Make cli.py script 3.6 compatible

charms/mariadb/config.yaml
Mariadb actually requires the password to be set, it will not automatically generate one.
Fixes #86
=> Fix mariadb option documentation

scripts/cli.py
We don't want to display stderr when only getting output.
Fixes #105
=> Hide stderr in get_output for cli.py

scripts/cli.py
Clarifies ambassador auth password handling and fixes erroneous command reference.
Fixes #106
=> Wording and documentation improvements for cli.py

charms/ambassador-auth/config.yaml, charms/ambassador-auth/reactive/ambassador_auth.py
It's otherwise confusing if the default is `''` and yet you need to login with `admin`. Also forces a username to be set instead of silently picking admin by default.
=> Default ambassador auth username to admin

scripts/cli.py
microk8s.status --wait-ready doesn't give sufficient information about storage status, so we wait specifically for the StorageClass to exist before proceeding with bootstrap.
Also introduces function to handle waiting for command to become ready.
=> Wait for microk8s storage to fully come up before bootstrapping

README.md, scripts/cli.py
Also remove `remove-from` / `teardown` CLI methods, in favor of steering people towards the regular juju commands.
Fixes #112
=> Add removal instructions to README

charms/ambassador-auth/metadata.yaml, charms/ambassador/metadata.yaml, charms/argo-controller/metadata.yaml, charms/argo-ui/metadata.yaml, charms/jupyter-controller/metadata.yaml, charms/jupyter-web/metadata.yaml, charms/katib-controller/metadata.yaml, charms/katib-manager/metadata.yaml, charms/katib-ui/metadata.yaml, charms/metacontroller/metadata.yaml, charms/minio/metadata.yaml, charms/modeldb-backend/metadata.yaml, charms/modeldb-store/metadata.yaml, charms/modeldb-ui/metadata.yaml, charms/pipelines-api/metadata.yaml, charms/pipelines-dashboard/metadata.yaml, charms/pipelines-persistence/metadata.yaml, charms/pipelines-scheduledworkflow/metadata.yaml, charms/pipelines-ui/metadata.yaml, charms/pipelines-viewer/metadata.yaml, charms/pytorch-operator/metadata.yaml, charms/redis/metadata.yaml, charms/seldon-api-frontend/metadata.yaml, charms/seldon-cluster-manager/metadata.yaml, charms/tensorboard/metadata.yaml, charms/tf-job-dashboard/metadata.yaml, charms/tf-job-operator/metadata.yaml, charms/tf-serving/metadata.yaml
Pod spec v2 broke backwards compatibility with 2.6, so disallow the charms from getting deployed by it.
=> Add min-juju-version to charms' metadata

scripts/cli.py
Previous Juju beta versions were probably just buggy in their requirement of the CLI param, and now that's been fixed in rc1 so that it's unnecessary.
Fixes #128
=> Remove explicit operator storage while deploying

scripts/cli.py
cli.py recommends a command that doesn't exist, fix it to recommend a command that does exist.
Fixes #130
=> Fix bad command suggestion in cli.py info output

scripts/cli.py
There's currently a bug in Juju that requires the `--all` flag, but it won't hurt going forward to include the flag anyways.
=> List all clouds when deploying in cli.py

charms/katib-controller/files/trial-crd.yaml, charms/katib-manager/config.yaml, charms/katib-manager/metadata.yaml, charms/katib-manager/reactive/katib_manager.py, charms/katib-ui/reactive/katib_ui.py
Although the dashboard has been synced to 0.6, Katib 0.6 doesn't support custom mysql db service locations, so we need to use 0.7. Keeps Katib current with upstream's 0.7 release candidate version.
=> Sync Katib charms with current 0.7rc from upstream

tests/Dockerfile.mnist, tests/pipelines/common.py, tests/pipelines/mnist.py, tests/test_pipelines.py
The pipelines DSL now supports passing large amounts of data natively, instead of having to manually shuffle it back and forth with minio.
=> Remove hardcoded minio usage in example pipeline

charms/pipelines-persistence/metadata.yaml, charms/pipelines-persistence/reactive/pipelines_persistence.py
It needs some permissions to function properly, and pod spec v2 also has different syntax for skipping service creation.
=> Update pipelines-persistence to pod spec v2

bundle-lite.yaml
Currently only for development purposes, but would also be useful for a regular MicroK8s deploy.
=> Add lightweight bundle alternative

charms/pipelines-viewer/reactive/pipelines_viewer.py
Upgrades to pod spec v2, which allows setting necessary permissions.
=> Add pipelines-viewer permissions

charms/katib-manager/reactive/katib_manager.py
The config got updated, and the Python code wasn't.
=> Fix katib manager port reference

charms/argo-controller/config.yaml
Required for smooth microk8s.enable kubeflow experience
=> Skip certificate checking in argo controller by default

charms/argo-controller/config.yaml, charms/pipelines-api/files/condition.yaml, charms/pipelines-api/files/exit_handler.yaml, charms/pipelines-api/files/parallel_join.yaml, charms/pipelines-api/files/sequential.yaml, charms/pipelines-api/files/xgboost_training_cm.yaml, pipeline-samples/condition.py, pipeline-samples/exit_handler.py, pipeline-samples/parallel_join.py, pipeline-samples/sequential.py, pipeline-samples/xgboost_training_cm.py
We no longer have to hack around kubelet certificates and insecure APIs, but the upstream workflows haven't been recompiled with a more recent version of kfp, so we still need to inject those into the docker image.
=> Switch to PNS executor by default in Argo

tests/test_pipelines.py
Newer versions of kfp don't match underscores and dashes, param names must match exactly.
=> Update pipeline param names for newer kfp versions

scripts/cli.py
So that e.g. switching models to work on something else while Kubeflow deploys in the background doesn't break the deploy process.
=> Specify Juju model during deploy process

charms/ambassador/metadata.yaml, charms/argo-controller/metadata.yaml, charms/argo-ui/metadata.yaml, charms/jupyter-controller/metadata.yaml, charms/jupyter-web/metadata.yaml, charms/katib-controller/metadata.yaml, charms/katib-manager/metadata.yaml, charms/katib-ui/metadata.yaml, charms/kubeflow-dashboard/metadata.yaml, charms/metacontroller/metadata.yaml, charms/metadata-api/metadata.yaml, charms/metadata-ui/metadata.yaml, charms/minio/metadata.yaml, charms/modeldb-backend/metadata.yaml, charms/modeldb-store/metadata.yaml, charms/modeldb-ui/metadata.yaml, charms/pipelines-api/metadata.yaml, charms/pipelines-persistence/metadata.yaml, charms/pipelines-scheduledworkflow/metadata.yaml, charms/pipelines-ui/metadata.yaml, charms/pipelines-viewer/metadata.yaml, charms/pytorch-operator/metadata.yaml, charms/redis/metadata.yaml, charms/seldon-api-frontend/metadata.yaml, charms/seldon-cluster-manager/metadata.yaml, charms/tensorboard/metadata.yaml, charms/tf-job-dashboard/metadata.yaml, charms/tf-job-operator/metadata.yaml, charms/tf-serving/metadata.yaml
2.7 is now stable, so no need to rely on an RC version
Fixes #153
=> Bump minimum Juju version to 2.7.0 for each charm

charms/dex-auth/reactive/dex_auth.py
Previously, any changes in config to oidc-gatekeeper weren't getting updated for dex-auth.
=> Restart dex-auth pod on oidc-client relation changes

.travis.yml, README.md, charms/ambassador/metadata.yaml, charms/ambassador/reactive/ambassador.py, scripts/cli.py
Uses juju-generated ELB in AWS instead of kubernetes worker IP. Also uses metallb on microk8s, unless a public address is manually specified. Also updates README with instructions for overriding public address.
=> Better public address handling for AWS and microk8s

charms/cert-manager-controller/reactive/controller.py, charms/cert-manager-webhook/reactive/webhook.py, scripts/cli.py
Previously, it was only tested on a cluster without RBAC enabled.
=> Make cert-manager work with RBAC-enabled clusters

charms/cert-manager-webhook/reactive/webhook.py
There can be a race condition where a certificate secret exists but hasn't yet been populated with an actual certificate. This checks for that condition in cert-manager-webhook.
=> Handle race condition with empty certificate secret

charms/dex-auth/reactive/dex_auth.py, charms/dex-auth/wheelhouse.txt
Check that we're the leader before calling pod spec set, due to Juju bug #1875481. Also, Juju 2.8 uses a different version of Python than the charm snap, so we can't install precompiled dependencies via the wheelhouse.txt mechanism, we have to handle installing during import.
=> Fix dex-auth charm for Juju 2.8

scripts/cli.py
There are some hardcoded references to this service in upstream Kubeflow
=> Add ml-pipeline service alias for pipelines-api

README.md
- Made clear that you need Ubuntu to install this bundle. 
- Format Mac/Windows instructions as a block quote so users don't assume that the entire setup is **only** for Mac/Windows
Fixes #216
=> Clarified setup instructions

.github/workflows/publish-bundle.yaml
Goes in conjunction with https://github.com/knkski/rust-libjuju/commit/6cf05b5
First publishes the full bundle, and uploads the charms from the local repo. Then publishes the lite and edge bundles, reusing the already-pushed charms from the full bundle upload. This ensures that the various bundles actually use the same charm revisions, for sanity's sake.
=> Order bundle releases

.github/workflows/publish-bundle.yaml
Though YAML allows spaces in keys, GitHub doesn't like them
=> Fix github action name

.github/workflows/test-microk8s.yaml, tests/test_kubectl.py
microk8s will now create some Calico-related CRDs by default, so test that the CRDs we care about are a subset of the total CRDs, instead of exactly equal.
=> Fix tests on microk8s edge

scripts/cli.py
The lite bundle includes the dashboard, and so needs the public address to be set.
=> Fix handling of lite bundle in cli.py

.github/workflows/test-microk8s.yaml
Failing fast means we don't find out if one job in particular is flakey or if it's a general issue.
=> Don't fail fast on Github CI actions

docs/authentication.md, docs/img/dex-authenticated.svg, docs/img/dex-callback.svg, docs/img/dex-login.svg, docs/img/dex-unauthenticated.svg, docs/img/oidc.svg
The nested svg images for the kubeflow, oidc, etc icons fail to render in browser and the animated svg's contained some errors. I regenerated the svg's with the icons imported directly to avoid the nesting issue. I also fixed up the oidc.svg box sizing as it was not centered and rectangular rather than square.
=> Fixed svg images for authentication docs

scripts/cli.py
Uses e.g. `microk8s enable` instead of `microk8s.enable`, since that syntax is now supported.
=> Microk8s usage updates

bundle-edge.yaml, bundle-lite.yaml, bundle.yaml
Each charm has now been promulgated, and so can use e.g. `foo` instead of `cs:~kubeflow-charmers/foo`. Additionally, juju-bundle will now build a charm locally if the charm source is sitting under `charms/`, so the `source:` tags can be removed.
=> Simplify bundle yamls

scripts/cli.py
Parsing the output from juju list-clouds can return `None`. Replace that value with `{}`, so that the call to `.items()` succeeds, and just returns an empty list.
=> Handle empty output from juju list-clouds

.github/workflows/publish-bundle.yaml
Otherwise, with the switch to charm URLs of just e.g. `minio`, the charms get published to `cs:~username/minio`, where `username` is the username for the credentials used.
=> Specify namespace when publishing bundle in CI

charms/katib-controller/reactive/katib_controller.py, scripts/cli.py
Create a webhook with the same name as the one that the upstream code attempts to create, since we create it correctly, and the upstream code will simply skip creating it if it already exists.
=> Better katib-controller webhook handling

.github/workflows/test-microk8s.yaml, charms/katib-controller/config.yaml, charms/katib-controller/metadata.yaml, charms/katib-controller/reactive/katib_controller.py, charms/katib-manager/reactive/katib_manager.py, tests/pipelines/katib.py
The katib-controller code really, really wants to overwrite bits of Kubernetes infrastructure, which includes bits of infra that the charm sets up via Juju. The upstream code also is hardcoded to set the service up as using the label `app: katib-controller`, whereas Juju labels the pod as `juju-app: katib-controller`.
So, the upstream code got forked to just set up the infrastructure correctly, and this charm can just use the r.c.c docker image that uses that forked code.
=> Work around katib-controller behavior

bundle-lite.yaml, bundle.yaml
Juju 2.9 requires `cs:` prefix to use the `-N` version specifier, otherwise it will look at charmhub.io for the charm, which doesn't support that syntax.
=> Fixing istio charm store references

charms/jupyter-controller/reactive/jupyter_controller.py
If the relation changes, make sure to recall pod-spec-set.
=> Fix jupyter-controller / istio relation

.github/workflows/test-microk8s.yaml
We are getting some failures due to `juju bootstrap` being `sudo`ed due to `scripts/cli.py` usages being `sudo`ed. Uses `sg microk8s -c <...>` where necessary instead of `sudo <...>` to fix that issue. Also switches to `balchua/microk8s-actions` for installing MicroK8s, as that sets up `kubectl` correctly so that we can use that instead of `microk8s kubectl`, thus avoiding the need for `sg` or `sudo`. Also switches all `juju` commands to be `sudo`-less, since the bootstrapping no longer uses `sudo`.
=> Fix juju sudo error in CI tests

.github/workflows/publish-bundle.yaml
The snap is strictly confined, and can't pull down git dependencies due to a permissions error.
=> Use charmcraft pip install instead of snap

poetry.lock, pyproject.toml, requirements.txt, test-requirements.txt, tests/test_kubectl.py
Uses poetry to maintain dependency versions, with requirements.txt exported after poetry resolves versions.
=> Switch to poetry for listing dependencies

tests/test_selenium.py
Attempts to manually verify that the URL is correct, instead of just using `wait.until(url_to_be...`, and refreshes the page in between attempts.
=> Make selenium notebook test more robust

charms/pipelines-api/reactive/pipelines_api.py
Some pipelines seem to fail on AKS due to pipeline-runner not being a clusterrole.
=> Make pipeline-runner role a clusterrole

charms/admission-webhook/src/charm.py
Otherwise Kubernetes encounters a certificate error due to Go breaking backwards compatibility with Common Name certificates.
Fixes #308
=> Update admission-webhook cert handling

.github/workflows/publish-bundle.yaml
We shouldn't need to publish a new bundle for changes outside of `charms/` or the bundle YAML files.
=> Restrict publishing job to relevant path changes

scripts/cli.py
This change allows bootstrap with controller config:
```console
$ python3 ./scripts/cli.py microk8s setup --test-mode --config caas-image-repo=test-repo --config='logging-config="<root>=TRACE"'
```
=> Making './scripts/cli.py microk8s setup' support controller config;

.github/workflows/test-microk8s.yaml
Will be fixed by https://github.com/canonical/minio-operator/pull/9, but that's blocked by switching over to the new argo-operators repo:
https://github.com/canonical/argo-operators
=> Disable restart testing

.github/workflows/test-microk8s.yaml
We don't want to fail the entire pod log schlepping if a single pod fails due to still being initializing.
=> Better handling of pod logs in CI

README.md
Link to mnist example is broken as the file it points to has been removed. I think updating the link to point to this [example](https://github.com/canonical/tfjob-operator/blob/master/examples/mnist.yaml) is a good option as it is the 'hello world' equivalent of a TFJob.
Fixes #372
=> README.md: updates broken link to nonexistent file

bundle-edge.yaml, bundle-lite.yaml, bundle.yaml
Looks like we forgot to update the `kfp-*` charms' stable channels after committing a fix:
Fixes https://github.com/canonical/kfp-operators/issues/16
=> Update to latest stable kubeflow-pipelines versions

.github/workflows/publish.yaml, charmcraft.yaml
Removes CLI flags that are now unnecessary with bundle being split up, and switches to `juju-bundle` snap. Also adds `charmcraft.yaml` file for forwards compatibility with uploading via charmcraft.
=> Update bundle publishing

README.md
Creating a namespace with the same name as the username leads to pipeline tests to fail.
Add a warning in step one. Also fixed some markdown formatting issues across the document.
=> Add warning about namespace creation before running tests

README.md
Microk8s no longer supports the kubeflow add-on, so I chose to add a note on the readme file to make the necessary clarifications.
=> Trivial docfix for onboarding task

.gitignore, docs/examples/mnist.yaml, tests/pipelines/mnist.py
This PR updates the links where the artifact files can be downloaded since they aren't available on people.canonical.com anymore. The mnist file referenced in [documentation](https://charmed-kubeflow.io/docs/kubeflow-basics) has been re-compiled.
=> Update mnist.yaml and artifact links

releases/1.6/beta/kubeflow-lite/README.md, releases/1.6/beta/kubeflow-lite/bundle.yaml, releases/1.6/beta/kubeflow-lite/charmcraft.yaml, releases/1.6/beta/kubeflow/README.md, releases/1.6/beta/kubeflow/bundle.yaml, releases/1.6/beta/kubeflow/charmcraft.yaml, releases/1.6/edge/kubeflow-lite/README.md, releases/1.6/edge/kubeflow-lite/bundle.yaml, releases/1.6/edge/kubeflow-lite/charmcraft.yaml, releases/1.6/edge/kubeflow/README.md, releases/1.6/edge/kubeflow/bundle.yaml, releases/1.6/edge/kubeflow/charmcraft.yaml
Create edge and beta bundle files with upgraded components versions
> NOTE: unchecked items are the ones whose version is still under discussion/missing, and thus it hasn't been updated in the bundles definition. Check the item ONLY after modifying the bundle files.
The following versions were extracted from [kubeflow/manifests README.md](https://github.com/kubeflow/manifests/#kubeflow-components-versions) and kubeflow/manifests#2242:
- kubeflow/manifests#2207
- kubeflow/manifests#2194
- Kubernetes deprecation [guide](https://kubernetes.io/docs/reference/using-api/deprecation-guide/)
=> add 1.6 edge and beta bundle files

releases/1.6/stable/kubeflow-lite/README.md, releases/1.6/stable/kubeflow-lite/bundle.yaml, releases/1.6/stable/kubeflow-lite/charmcraft.yaml, releases/1.6/stable/kubeflow/README.md, releases/1.6/stable/kubeflow/bundle.yaml, releases/1.6/stable/kubeflow/charmcraft.yaml
Adds stable 1.6 bundle definitions for kubeflow and kubeflow-lite. Please note this definitions expect all the charms in them to be uploaded in their <version>/stable channels.
=> feat: add stable 1.6 bundle definitions

releases/1.7/beta/kubeflow/README.md, releases/1.7/beta/kubeflow/bundle.yaml, releases/1.7/beta/kubeflow/charmcraft.yaml, releases/1.7/edge/kubeflow/README.md, releases/1.7/edge/kubeflow/bundle.yaml, releases/1.7/edge/kubeflow/charmcraft.yaml
Create edge and beta bundle files with upgraded components versions for 1.7 release. Please note this PR is adding the full bundle, as kubeflow-lite may be removed in this release.
> NOTE: unchecked items are the ones whose version is still under discussion/missing, and thus it hasn't been updated in the bundles definition. Mark the item ONLY after modifying the bundle files.
The following versions are extracted from kubeflow/manifests#2359:
The following versions are either extracted from the upstream project or decided by the Charmed Kubeflow team:
1. Should we add knative and kserve in the kubeflow-bundle?
2. Is kubeflow-lite still a thing for 1.7?
3. Seldon v2 is out, should we make the big jump? - Not for now
4. Should we stop maintiaining mlmd, metacontroller-operator?
- …
=> add 1.7 edge and beta bundle definitions and define component versions

releases/1.7/beta/kubeflow/bundle.yaml, releases/1.7/edge/kubeflow/bundle.yaml
update bundle definition in 1.7/beta and 1.7/edge with missing `trust: true` for `knative-eventing` and `knative-serving` charms.
=> fix: add trust to knative-eventing and knative-serving

releases/latest/edge/bundle.yaml
This PR:
* points all charms to latest/edge to reflect the real latest/edge bundle
* configure kserve in serverless mode with charm configurations and relations
=> Changes in bundle.yaml 

tests-bundle/1.7/test_1dot7.py, tests-bundle/1.7/test_tutorial.py
Description: Adds invocation of the the kubeflow-profiles `create-profile` action to automatically create a user `Profile` during testing so that we do not get prompted with the first-time-login box to create a user in the dashboard
=> Automatically add user profile during bundle tests

releases/1.7/edge/kubeflow/bundle.yaml
* Deploy KFP API with trust
* Mandatory since [charm rewrite](https://github.com/canonical/kfp-operators/commit/58615a72a11fbac5fafad1796b04fcb1a7be1c31) following the sidecar pattern 
* Deploy Katib DB manager with trust
* Mandatory since [charm rewrite](https://github.com/canonical/kfp-operators/commit/58615a72a11fbac5fafad1796b04fcb1a7be1c31) following the sidecar pattern 
* Integrate KFP API charm with MySQL
* Use the `relational-db` relation instead of the default `mysql` 
* https://github.com/canonical/kfp-operators/issues/201
* Integrate Katib DB manager with MySQL
* Use the `relational-db` relation instead of the default `mysql` 
* https://github.com/canonical/katib-operators/issues/74
* Integrate KServe with Istio
=> feat: Update 1.7 edge bundle

releases/1.7/beta/kubeflow/bundle.yaml, releases/1.7/stable/kubeflow/bundle.yaml
* Deploy KFP API with trust
* Mandatory since [charm rewrite](https://github.com/canonical/kfp-operators/commit/58615a72a11fbac5fafad1796b04fcb1a7be1c31) following the sidecar pattern 
* Deploy Katib DB manager with trust
* Mandatory since [charm rewrite](https://github.com/canonical/kfp-operators/commit/58615a72a11fbac5fafad1796b04fcb1a7be1c31) following the sidecar pattern 
* Integrate KFP API charm with MySQL
* Use the `relational-db` relation instead of the default `mysql` 
* https://github.com/canonical/kfp-operators/issues/201
* Integrate Katib DB manager with MySQL
* Use the `relational-db` relation instead of the default `mysql` 
* https://github.com/canonical/katib-operators/issues/74
* Integrate KServe with Istio
=> Update 1.7/stable/beta bundle definitions for 1.7 Patch 1

releases/1.7/edge/kubeflow/bundle.yaml
Update 1.7/edge to use `edge` channel for `mysql-k8s` charms, since there is a known issue on `stable`. See canonical/mysql-k8s-operator#239. Note that this change should not be promoted to stable.
Signed-off-by: Orfeas Kourkakis <orfeas@arrikto.com>
=> fix: Update 1.7/edge bundle

.github/workflows/scan-images.yaml
Automation of CVE scanning requires a workflow that perform retrieval and scan of all images in the bundle.
This workflow relies on input filename specified when workflow is triggered. It usese `kubeflow-ci/scripts/image/` tools to retrieve images, scan for CVEs and produce Trivy reports and scan summary file. Reports and scan summary are uploaded to the job artifacts.
Relies on the following to be merged:
https://github.com/canonical/seldon-core-operator/pull/163
https://github.com/canonical/kubeflow-ci/pull/80
- Workflow that performs scanning of all images in bundle.
=> feat: scan of images in bundle

releases/1.7/stable/kubeflow/bundle.yaml
Bundle file does specify which branch was used to build released version of the charm.
This branch is useful when scanning for CVEs in workload container and can be re-used to pull all related images to create archives for airgapped environment setup.
Branch name is added to 1.7/stable bundle file.
- Updated bundle yaml file with branch names that need to be correspond to specified channel.
=> feat: updated bundle with branch names

releases/latest/edge/bundle.yaml
This adds the dashboard links relations to the bundle, as required by the implementation of the [dynamic dashboard PR](https://github.com/canonical/kubeflow-dashboard-operator/pull/134)
=> updated latest/edge bundle.yaml to use dashboard links

.github/workflows/scan-images.yaml
GH runners are running out of space. Need to add cleanup actions to save space.
- Added space saving step to workflow.
- Removed 1.6 from scan.
=> fix: save space

.github/workflows/deploy-eks.yaml
Fix `deploy-eks.yaml` workflow so that in the case of failure, it deletes the cluster after getting relevant logs.
=> ci: Deploy EKS workflow deletes cluster after getting logs

releases/latest/edge/bundle.yaml
Trust rewritten kfp charms that were rewritten following the sidecar pattern. These are:
- kfp-persistence
- kfp-profile-controller
- kfp-schedwf
- kfp-ui
- kfp-viewer
Merge ONLY after https://github.com/canonical/kfp-operators/pull/288 is merged (the rest of the components have already been merged).
=> latest/edge: Trust kfp charms rewritten with sidecar

tests-bundle/1.7/test_release_1-7.py
Fix `test_profile_creation` test not waiting for profile to be created before being marked as `PASSED` and moving onto next test.
=> tests-bundle: Add action.wait() to test_profile_creation

tests-bundle/1.7/test_release_1-7.py
tests-bundle: Fix profile creation by modifying profilename. The error we were getting is 
```
lightkube.core.exceptions.ApiError: Profile.kubeflow.org "admin@email.com" is invalid: metadata.name: Invalid value: "admin@email.com": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```
=> tests-bundle: Fix profile creation by modifying profilename

.github/workflows/full-bundle-tests.yaml, .github/workflows/release-bundle-to-charmhub.yaml, .github/workflows/run-tests-and-publish-bundle.yaml, releases/latest/beta/README.md, releases/latest/beta/charmcraft.yaml, releases/latest/edge/README.md, releases/latest/edge/charmcraft.yaml, scripts/get_bundle_path.py, scripts/get_bundle_test_path.py, scripts/get_releases_affected.py
This PR adds CI that automatically publishes bundle releases to Charmhub, if they have been modified/affected by a PR-commit pushed to `main`. Task https://warthogs.atlassian.net/browse/KF-4053.
In more detail, this introduces:
- Workflow that gets triggered when there are changes in a `releases` directory and only during push to `main` and it:
- Detects which releases have been affected
- Triggers the reusable WF, for each of the releases affected, in order to run bundle tests on it and if they succeed, it publishes the new bundle to Charmhub.
- reusable WF to run tests and publish to charmhub for a single release
- changes to full-bundle-tests workflow to make it reusable (by other WFs)
- script that, according to files changed, returns which bundle releases have been affected.
- script …
=> ci: Publish bundle to charmhub

.github/workflows/scan-images.yaml
Image scan script was updated to use another Python script. As a result, update to workflow is required.
Issue and solution is described in https://github.com/canonical/bundle-kubeflow/issues/667
Kubeflow CI PRs:
https://github.com/canonical/kubeflow-ci/pull/104
https://github.com/canonical/kubeflow-ci/pull/105
- Updated scan images section of workflow to work with new kubeflow-ci scripts, i.e. two scripts: one for scanning, one for generating summary.
Test run of the workflow using PR branch: https://github.com/canonical/bundle-kubeflow/actions/runs/5917711692/job/16046303693
=> fix: update workflow to accommodate new script

releases/latest/edge/bundle.yaml
In order for image retrieval scripts that are used in image scanning action (in this repository) to properly checkout source code for `main` branch an update was made bundle definition (see comments below).
More details in: https://github.com/canonical/bundle-kubeflow/issues/679
- Added branches to latest/edge/bundle.yaml. This is required to enable image retrieval scripts to properly checkout source code.
- Updated MySQL K8S charm to point to 8.0/edge
=> feat: update bundle with branches

.github/workflows/scan-images.yaml, releases/latest/edge/bundle.yaml
Update to scan image workflow is needed to scan latest/edge bundle.
More details are in: https://github.com/canonical/bundle-kubeflow/issues/679
- Added latest to scan matrix.
- Workflow is redesigned to improve handling of multipole releases and avoid running scans on not required bundles.
=> feat: added latest to scan

releases/latest/edge/bundle-airgap.yaml
Output from the effort in #680
=> feat: add bundle definition for airgapped envs

.github/workflows/scan-images.yaml
Update the way report names are generated in workflow. More details are in: https://github.com/canonical/bundle-kubeflow/issues/695
- Modified workflow to parse release-risk according to new setup and use output varible in creating report names.
GH runner log:https://github.com/canonical/bundle-kubeflow/actions/runs/6172712752
=> fix: modified workflow to parse release-risk

releases/latest/edge/bundle-airgap.yaml
the metacontroller image was downgraded in https://github.com/canonical/metacontroller-operator/pull/85
this change needs to be reflected in the airgap bundle definition for `latest/edge`
=> fix: change metacontroller image tag in bundle-airgap.yaml

releases/latest/beta/bundle.yaml, releases/latest/edge/bundle-airgap.yaml, releases/latest/edge/bundle.yaml
Deploy argo-controller with trust as a result of the charm rewrite in canonical/argo-operators#127
=> build: deploy argo-controller with trust

releases/1.7/edge/kubeflow/bundle.yaml
Add `_github_repo_branch` metadata in `bundle.yaml` file which is needed by script that gathers all images for bundle deployment.
=> 1.7/edge: Add _github_repo_branch metadata to bundle.yaml file

releases/1.7/edge/kubeflow/airgap/bundle-airgap.yaml, releases/1.7/edge/kubeflow/airgap/podspec_script.sh
This PR creates the files needed to deploy CKF `1.7/edge` in an airgapped environment. This is part of effort https://github.com/canonical/bundle-kubeflow/issues/705.
At the moment, charms in `1.7/edge` are split into sidecar and podspec:
- admission-webhook *
- argo-controller *
- argo-server
- jupyter-controller *	
- katib-controller	
- kfp-persistence *  
- kfp-profile-controller *
- kfp-schedwf *
- kfp-ui *
- kfp-viewer *	  
- kfp-viz *
- kubeflow-volumes	
- minio	
- oidc-gatekeeper *
- tensorboard-controller *
- tensorboards-web-app *
\* Those noted with asterisk are rewritten in sidecar in `latest/edge`.
- dex-auth	
- istio-ingressgateway	    	
- istio-pilot
- jupyter-ui	
- katib-db	
- katib-db-manager
- katib-ui	
- kfp-api	
- kfp-db	
- knative-eventing	
- knative-operator	
- …
=> airgap(1.7/edge): Create bundle-airgap.yaml and podspec_script.sh

releases/latest/edge/bundle.yaml
Add trust: true to oidc-gatekeeper charm in latest/edge bundle.yaml file.
Fixes #708
=> latest/edge: Trust oidc-gatekeeper

releases/latest/edge/airgap/podspec_script.sh, releases/latest/edge/bundle.yaml
argo-server charm is not utilized in the charmed kubeflow bundle. The UI is not accessible to users atm.
This removes it from latest/edge bundle.yaml and  latest/edge air-gapped bundle.
=> fix: remove argo-server from latest/edge

releases/latest/edge/bundle.yaml
Add [pvcviewer-operator](https://github.com/canonical/pvcviewer-operator) to `latest/edge` bundle.yaml. I didn't include this in `bundle-airgap.yaml` but filed this issue https://github.com/canonical/bundle-kubeflow/issues/718.
=> latest/edge: Add pvcviewer-operator to bundle.yaml

releases/latest/beta/bundle.yaml
Bring updates from `latest/edge` to `latest/beta` since we will create `1.8/beta` using `latest/beta`.
=> latest/beta: Update according to latest/edge

releases/1.8/beta/bundle.yaml
* point `kfp-operators` charms to `2.0/edge` due to https://github.com/canonical/kfp-operators/issues/343
* point `seldon-controller-manager` charm to `latest/edge` due to https://github.com/canonical/seldon-core-operator/issues/218
* point `kubeflow-profiles-operator` charm to `1.7/edge` due to https://github.com/canonical/notebook-operators/issues/309
=> fix: update 1.8/beta bundle definition

.github/workflows/run-tests-and-publish-bundle.yaml
Follow-up from https://github.com/canonical/bundle-kubeflow/pull/722
We'll also need to ensure the publish action does not depend on the, now commented out, `run-tests` step
=> CI step for publishing should not depend on tests

releases/1.8/beta/bundle.yaml
modifies the `1.8/beta` bundle definition to include `argo-controller` `3.3/stable` rather than `latest/edge` due to issue https://github.com/canonical/kfp-operators/issues/345
=> fix: pin argo to 3.3/stable in 1.8/beta

releases/1.8/beta/kubeflow/bundle.yaml
changes `argo-controller` channel in `1.8/beta` bundle definition to `latest/beta`, `argo-controller` was originally pinned to `3.3/stable` due to issue https://github.com/canonical/kfp-operators/issues/345, the issue is now resolved so we can update argo.
=> fix: argo-controller channel in 1.8/beta

releases/1.7/beta/kubeflow/bundle.yaml, releases/1.7/edge/kubeflow/bundle.yaml, releases/1.7/stable/kubeflow/bundle.yaml
changes the channel of kfp charms from `2.0` to `2.0-alpha.7` in 1.7 bundle definitions to accommodate for the upcoming release.
kfp charms of 1.7 will now point to channel `2.0-alpha.7`, so that kfp charms of 1.8 can point to channel `2.0`.
An announcement on discourse will be made for CKF 1.7 users.
=> feat: point kfp charms to 2.0-alpha.7 in 1.7 bundles

releases/latest/edge/bundle.yaml
The latest/edge bundle should be deployed with mlmd and envoy. This commit adds those charms and their required relations. This also sets the default series for the pvcviewer-operator to focal to avoid pulling from another base.
=> chore: update bundle definition with mlmd, envoy, kfp-metadata-writer

releases/1.8/beta/kubeflow/bundle.yaml
Point all CKF charms to their corresponding 1.8/beta channel. This PR should be merged once the charms are available in the correct track.
=> chore: point all CKF charms to 1.8/beta channel to match release

releases/1.8/edge/kubeflow/README.md, releases/1.8/edge/kubeflow/bundle.yaml, releases/1.8/edge/kubeflow/charmcraft.yaml, tests-bundle/1.8/test_release_1-8.py
This PR adds a bundle definition for CKF 1.8/edge, which includes newer charms like mlmd, envoy, kfp-metadata-writer, and pvcviewer-operator.
All the tracks correspond to the versions that were proposed in https://github.com/canonical/bundle-kubeflow/issues/643.
=> chore: add 1.8/edge bundle definition

.github/workflows/scan-images.yaml
Extend the GH Action that scans all images to also run on 1.8.
=> Update image scanning to include 1.8

scripts/get_bundle_test_path.py
Update scripts to return test path for 1.8 (`./tests-bundle/1.8/`) when the release is `latest/edge`.
=> scripts: Update latest/edge to run 1.8 tests

.github/workflows/full-bundle-tests.yaml, scripts/get_release_from_bundle_source.py, tests-bundle/1.8/requirements.txt, tests-bundle/1.8/test_release_1-8.py
This PR integrates the UATs to [full-bundle-tests.yaml](https://github.com/canonical/bundle-kubeflow/blob/main/.github/workflows/full-bundle-tests.yaml) workflow. The PR should be merged alongside https://github.com/canonical/charmed-kubeflow-uats/pull/56. Note that at the moment, the training-integration UAT will fail on self-hosted runners due to https://github.com/canonical/charmed-kubeflow-uats/issues/50. 
- Update [tests-bundle/1.8](https://github.com/canonical/bundle-kubeflow/tree/main/tests-bundle/1.8)
- Unpin juju in tests-bundle/1.8.
- Refactor workflow to use Aproxy, Python 3.8 and operator action
- Add UATs to workflow
- Add save debug artifacts to workflow
Fixes canonical/charmed-kubeflow-uats#7
In order to see the action live, you could go to Actions > Deploy bundle and run …
=> ci: Integrate UATs to full-bundle-tests.yaml

.github/workflows/scan-images.yaml
ci: Decrease root-reserve-mb to fit the new runner storage
addresses https://github.com/canonical/bundle-kubeflow/issues/813
=> ci: Decrease root-reserve-mb to fit the new runner storage

.github/workflows/deploy-eks.yaml, tests/integration/test_bundle_deployment.py, tox.ini
- Enable tests/integration to be able to run [last two supported versions](https://charmed-kubeflow.io/docs/supported-versions) (1.7 and 1.8). Details in the issue
- Adjust `deploy-eks.yaml` tox command to keep the workflow from testing.
This switches deploying from `edge` to `stable` since we were deploying `edge` 
due to https://github.com/canonical/mysql-k8s-operator/issues/239.
Closes #800
=> feat: Enable tests/integration to be able to run 1.7 and 1.8

releases/latest/edge/bundle.yaml
Trust kubeflow-volumes after it was rewritten in canonical/kubeflow-volumes-operator#125.
=> feat: Trust kubeflow-volumes

.github/workflows/full-bundle-tests.yaml
Update UATs environment used in `full-bundle-tests.yaml` used after changes in https://github.com/canonical/charmed-kubeflow-uats/pull/67.
=> fix(ci): Update uats environment used in full-bundle-tests.yaml

.github/workflows/deploy-to-aks.yaml
Run UATs in `deploy-to-aks.yaml` workflow after deploying CKF to an AKS cluster.
Example [run](https://github.com/canonical/bundle-kubeflow/actions/runs/8482618840/job/23242188217)
Closes #774
=> feat(ci): Run UATs in AKS workflow

releases/latest/edge/bundle.yaml
mlmd was recently refactored to use the sidecar pattern, which now requires this charm to be trusted as it applies k8s resources.
=> chore: trust mlmd due to refactor

releases/1.8/beta/kubeflow/bundle.yaml, releases/1.8/edge/kubeflow/bundle.yaml, releases/1.8/stable/kubeflow/bundle.yaml
adds the `_github_dependency_repo_name` and `_github_dependency_repo_branch` attributes to `mysql-k8s-operator` charm in the 1.8 bundle yaml.
This is needed for airgapped, so that the `get-all-images.sh` script can get the image for the mysql charm, as similarly done for the [1.7 bundle](https://github.com/canonical/bundle-kubeflow/blob/main/releases/1.7/stable/kubeflow/bundle.yaml#L73C1-L74C41).
Related to #889.
=> fix: add github dependency attributes to mysql charm in 1.8 bundle

.github/cluster.yaml, .github/workflows/deploy-to-eks.yaml
Closes https://github.com/canonical/bundle-kubeflow/issues/802 and https://github.com/canonical/charmed-kubeflow-uats/issues/55
The UATs are failing due to and https://github.com/canonical/bundle-kubeflow/issues/893
Example execution here: https://github.com/canonical/bundle-kubeflow/actions/runs/9254432418/job/25456220979
=> Run UATs on EKS for v1.8

.github/workflows/deploy-to-aks.yaml
Example run https://github.com/canonical/bundle-kubeflow/actions/runs/9004529983.
Closes #891 
EDIT:
Katib UAT fails but it failed previously as well #893
Training-operator UAT starts to failing after bumping k8s version #894
=> ci(aks): bump k8s version to 1.28

scripts/airgapped/prerequisites.sh, scripts/airgapped/requirements.txt, tests/airgapped/README.md, tests/airgapped/airgap.sh, tests/airgapped/ckf.sh, tests/airgapped/registry.sh, tests/airgapped/setup/prerequisites.sh, tests/airgapped/setup/setup.sh
Some changes to the airgapped script to use it for testing CKF 1.8
part of #889 
* use `sudo` to run microk8s commands, this is needed for strict microk8s
* pin `requests` dependency version until docker issue is resolved
* use `sudo` with `juju bootstrap microk8s` for strict microk8s
* install `python3-pip` before running `pip3 install`
* remove unrecognized arguments for `save-charms-to-tar.py`
=> fix: update the airgap scripts to work with 1.8

scripts/airgapped/get-all-images.sh, tests/airgapped/pipelines/README.md, tests/airgapped/pipelines/kfp-airgapped.ipynb, tests/airgapped/pipelines/pipelines-runner/Dockerfile, tests/airgapped/pipelines/pipelines-runner/README.md
part of #898 
* adds a notebook with a sample pipeline to test in airgapped
* adds the `pipelines-runner` image to use in the test
* adds README.md for pipelines test
* adds README.md for `pipelines-runner` image
* modifies the `get-all-images.sh` script to include the `pipelines-runner` image
=> feat: define test for pipelines in airgapped

tests/airgapped/airgap.sh
closes #897 
Adds a step in the `airgap.sh` script to create an Ingress object in the `kubeflow` namespace. This step allows us to access the dashboard from the host during airgapped testing.
=> airgapped: add step in script to expose the dashboard

releases/latest/edge/bundle.yaml
Needed due to canonical/katib-operators#185
Part of #893 fix
=> chore(latest): Add katib-controller katib-db-manager relation

tests/airgapped/README.md
closes #898 
Modifies the airgap testing README to include:
* instructions on deploying the bundle in airgapped
* configuring the dashboard
* instructions on testing the CKF components in airgapped linking to the relevant READMEs
=> feat: update airgapped testing README

scripts/airgapped/deploy-1.8.sh, tests/airgapped/README.md
addresses the comments received in https://github.com/canonical/bundle-kubeflow/pull/947#discussion_r1661248175 :
* updates the image for `kfp-profile-controller` charm in the deployment script, see updated image in the [`track/2.0` branch](https://github.com/canonical/kfp-operators/blob/track/2.0/charms/kfp-profile-controller/metadata.yaml#L14).
* modifies the README.md for testing in airgapped to remove the configure URL step. This was added incorrectly, the URL is already configured with the correct value in the deployment script for [dex-auth](https://github.com/canonical/bundle-kubeflow/blob/main/scripts/airgapped/deploy-1.8.sh#L28) and [oidc](https://github.com/canonical/bundle-kubeflow/blob/main/scripts/airgapped/deploy-1.8.sh#L141).
=> fix: update airgap deployment script and README.md

releases/latest/beta/bundle.yaml, releases/latest/edge/bundle.yaml
This commit updates the latest bundle definition to match the latest charm changes (e.g. config options, relations, trust, etc.)
Part of #958
=> chore: update latest/edge and latest/beta bundles

releases/latest/beta/bundle.yaml, releases/latest/edge/bundle.yaml
* Starting from CKF 1.9, seldon-core-operator is no longer maintained and should be removed from the bundle definition.
* Remove the katib-db-controller dup relation
=> chore: remove seldon-core-operator and remove dup relation

releases/latest/beta/bundle.yaml, releases/latest/edge/bundle.yaml
adds the missing relation introduced in https://github.com/canonical/training-operator/pull/177
=> add dashboard-links relation with training operator

releases/latest/beta/bundle.yaml, releases/latest/edge/bundle.yaml
Add relation between dex-auth and oidc-gatekeeper to share Dex's OIDC configuration.
Merge once all PRs for this feature are completed.
* https://github.com/canonical/dex-auth-operator/pull/211
* https://github.com/canonical/oidc-gatekeeper-operator/pull/163
* https://github.com/canonical/oidc-gatekeeper-operator/pull/164
=> chore: add relation for dex-oidc-config

tox.ini
Since this version of the bundle is now released, the automation should test with the right path to the 1.9/stable bundle.yaml.
=> chore: point the 1.9 bundle tests to 1.9/stable

tests/integration/test_bundle_deployment.py
The dex-issuer-config relation between oidc-gateeeker and dex-auth is not needed as the bundle already defines it. Removing it from the test file to avoid issues with juju applying a relation that already exists.
=> tests: remove extra relation between oidc and dex

test-reference/versions.json
Add CKF 1.9 stable as test reference so SQA can perform testing on all the combinations from the "ckf-1.9-stable" object.
=> chore: add 1.9-stable as test reference

.github/workflows/deploy-to-eks.yaml
This PR updates the "Create EKS cluster, deploy CKF and run bundle test" Github action for 1.9. It only changes the `deploy-to-eks.yaml` file to have updated defaults and descriptions when running the tests.
Closes #810.
=> Update the EKS tests for CKF 1.9

.github/workflows/scan-images.yaml
To ensure the scan results are using 1.9
=> ci: Update scanning actions to scan 1.9/stable and drop 1.7

releases/1.9/stable/bundle.yaml
Closes https://github.com/canonical/bundle-kubeflow/issues/1037
=> Add GitHub metadata for repo/branches in 1.9

.github/workflows/deploy-to-aks.yaml, .github/workflows/deploy-to-eks.yaml, scripts/gh-actions/parse_versions.py
Closes #1034 
This PR updates the `deploy-to-aks.yaml` and `deploy-to-eks.yaml` scripts to be able to handle values not enclosed in quotes. This is achieved by adding a `preprocess-input` job that processes the input to add quote characters and create a valid JSON array. An example of a valid input is:
```
1.8,1.9,latest
```
Additionally, the `preprocess-input` job removes space characters, this means that input like this is also handled properly:
```
1.8, 1.9, latest
```
=> Handle input not enclosed in quotes in "Deploy to AKS" and "Deploy to EKS" actions

charmcraft.yaml
The [Kubeflow bundle page on Charmhub](https://charmhub.io/kubeflow) does not have a designated discourse index topic. 
Add a link to a [home page topic](https://discourse.charmhub.io/t/charmed-kubeflow-home-page/14447) created  on discourse.charmhub.io. According to the [Juju/charmcraft documentation](https://juju.is/docs/sdk/charmcraft-yaml#heading--links), this must be done in the repository's `charmcraft.yaml` with the `link` key.
The discourse topic being linked has the following content:
```
Charmed Kubeflow (CKF) is an open-source, end-to-end, production-ready [MLOps](https://ubuntu.com/blog/what-is-mlops) platform on top of cloud-native technologies. It is intended for data scientists and ML engineers, providing an advanced toolkit to organise and scale their work.
For information …
```
=> Add Charmhub home page link to charmcraft.yaml

.github/workflows/scan-images.yaml, scripts/README.md, scripts/airgapped/README.md, scripts/get_all_images.py, scripts/get_bundle_images_sbom.py, tests/airgapped/1.8/katib/README.md, tests/airgapped/1.8/knative/README.md, tests/airgapped/1.8/pipelines/README.md, tests/airgapped/1.8/training/README.md, tests/airgapped/1.9/katib/README.md, tests/airgapped/1.9/knative/README.md, tests/airgapped/1.9/pipelines/README.md, tests/airgapped/1.9/training/README.md, tests/airgapped/README.md, tests/airgapped/ckf.sh
closes #1078 
* creates a python script that produces a `.tar.gz` containing the SBOMs for images in the bundle
* the script uses `syft` to produce the SBOMs
* the script uses the `syft` command advised by the security team
* the script relies on the existing `get-all-images.py` script to get the images used in kubeflow bundle
* renames the `get-all-images.py` module to `get_all_images.py` to be able to be imported from the new script
The .tar.gz produced can be found in [the team's Gdrive](https://drive.google.com/drive/folders/1vO8ipGMDryezuuNOaN995-OSKZepSf65?usp=drive_link)
**Note** this script does not apply to mlflow images, see https://github.com/canonical/bundle-kubeflow/issues/1078#issuecomment-2393150377 for how to generate the mlflow images SBOMs.
To get the SBOMs for kubeflow …
=> Add script to gather SBOMs for bundle images

.github/workflows/get-images-and-scan.yaml
Adding resource-dispatcher and namespace-node-affinity to the list of images to be scanned. While they do not necessarily belong to the bundle, they have to be scanned as part of the team's vulnerability response.
Fixes #1084
[Here's](https://github.com/canonical/bundle-kubeflow/actions/runs/11338619320/job/31532130158) a run for the proposed changes.
* [L530 and L531](https://github.com/canonical/bundle-kubeflow/actions/runs/11338619320/job/31532130158#step:3:531) show the images that were added for the 1.8 scan
* [L508 and L509](https://github.com/canonical/bundle-kubeflow/actions/runs/11338619320/job/31532130001#step:3:509) show the images that were added for the 1.9 scan
* [L508 and L509](https://github.com/canonical/bundle-kubeflow/actions/runs/11338619320/job/31532130369#step:3:509) …
=> ci: add missing charms to the Scan images workflow

.github/workflows/deploy-to-aks.yaml, .github/workflows/deploy-to-eks.yaml
Closes #1124.
This PR updates the `deploy-to-aks.yaml` and `deploy-to-eks.yaml` files to properly run on schedule.
The current issue that we had to overcome is explained [here](https://github.com/canonical/bundle-kubeflow/issues/1124#issuecomment-2476481572)
To fix this issue, I have condensed the 2 jobs into 1 job that always run, and the `if` statements are located inside run
Note that there is an issue when writing multiline strings to $GITHUB_OUTPUT, and that's why we run `tr` to remove all newline characters from the JSON output of `yq`.
=> Update AKS and EKS action to properly run on schedule

scripts/get_releases_affected.py
Updates the get releases script to include 1.9 bundle definitions.
See how it failed in https://github.com/canonical/bundle-kubeflow/actions/runs/12135466742/job/33834580034.
=> fix: update `get_releases_affected.py` with 1.9

.github/workflows/deploy-to-eks.yaml
Fix #1173
We can see that this work because the workflow was run from the PR's branch and 
1. The run failed exactly as in the linked issue in first attempt https://github.com/canonical/bundle-kubeflow/actions/runs/12137293822/job/33840248459#step:11:54 which means that it started creating a cloudformation but exited due to cluster creation failure
2. [Second attempt](https://github.com/canonical/bundle-kubeflow/actions/runs/12137293822/job/33840508643#step:11:42) started creating a CloudFormation stack instead of failing with: 
```
2024-12-03 09:38:10 [✖]  creating CloudFormation stack "eksctl-kubeflow-test-latest-cluster": operation error CloudFormation: CreateStack, https response error StatusCode: 400, RequestID: 2a8e4[22](https://github.com/canonical/bundle-kubeflow/actions/runs/12130 …
```
=> fix(ci): Cleanup CloudFormation stack when EKS cluster creation fails

.github/dependencies.yaml, .github/workflows/full-bundle-tests.yaml
Note that this doesn't bump PATCH version because it is removed in #1181.
Ref #1156
=> ci: bump juju to 3.6

.github/workflows/deploy-to-aks.yaml, .github/workflows/deploy-to-eks.yaml, .github/workflows/full-bundle-tests.yaml, pyproject.toml
Testing the upgrade of the Kubeflow UAT to Python 3.10 or 3.12, see https://github.com/canonical/charmed-kubeflow-uats/pull/137
The AKS and EKS runs have been positive using noble with python 3.12:
* [EKS](https://github.com/canonical/bundle-kubeflow/actions/runs/11978574125/job/33398942758)
* [AKS](https://github.com/canonical/bundle-kubeflow/actions/runs/11976053369/job/33390856205)
=> [KF-5958] Upgrade to Python3.10+

.github/cluster.yaml
Bump Ubuntu image used in EKS CI to 22.04 to:
1. use latest LTS available in eksctl. See https://eksctl.io/usage/custom-ami-support/#setting-the-node-ami-family.
2. resolve incompatibility between k8s version 1.31 and Ubuntu 20.04.
Fix #1200
See this example run https://github.com/canonical/bundle-kubeflow/actions/runs/13268173276/job/37040851598 from the PR's branch.
=> chore(ci): bump EKS ubuntu image to 22.04

.github/cluster.yaml, .github/workflows/deploy-to-eks.yaml, scripts/gh-actions/set_eks_sysctl_config.sh
Fixes #1210 
Investigation of the issue showed that trial pods for Katib consistently fail on EKS because of `metrics-logger-and-collector` container erroring out with the following message
```
(base) jovyan@workload-test-0:~$ kubectl logs -n 200 cmaes-example-4rm4bmt2-mkhrj -n admin -c metrics-logger-and-collector
I0224 12:38:04.158021      28 main.go:396] Trial Name: cmaes-example-4rm4bmt2
100.0%12:38:04.158578      28 main.go:139] 
100.6%12:38:04.160186      28 main.go:139] 
100.0%12:38:04.160318      28 main.go:139] 
119.3%12:38:04.160379      28 main.go:139] 
2025/02/24 12:38:04 FATAL -- failed to create Watcher
goroutine 6 [running]:
runtime/debug.Stack()
/usr/local/go/src/runtime/debug/stack.go:24 +0x5e
github.com/hpcloud/tail/util.Fatal({0xdce7f6?, 0x411a3b?}, {0x0, 0x0, 0x0}) …
```
=> type: fix EKS Katib failing test

.github/workflows/release-bundle-to-charmhub.yaml
Skips `tj-actions/changed-files` due to https://semgrep.dev/blog/2025/popular-github-action-tj-actionschanged-files-is-compromised/
=> ci: remove compromised action tj-actions/changed-files

.github/workflows/delete-aws-volumes.yaml, .github/workflows/get-images-and-scan.yaml, .github/workflows/release-bundle-to-charmhub.yaml, .github/workflows/run-tests-and-publish-bundle.yaml
Closes #1230 
Note than in this repo, the runners were on 22.04 so it is not urgent that we migrate them for now, but it's to be consistent with other repos
=> ci(chore): migrate GH runners to ubuntu 24.04

.github/workflows/deploy-to-aks.yaml, .github/workflows/deploy-to-eks.yaml
Replace github action with small bash script. This is to enhance
security since those workflows have access to credentials/repo's
secrets.
Example runs:
* AKS https://github.com/canonical/bundle-kubeflow/actions/runs/15445131023. AKS is expected to fail during cluster creation for 1.8 and 1.9 but envvars can be viewed in the steps.
* EKS https://github.com/canonical/bundle-kubeflow/actions/runs/15444359091/job/43469888979
=> tests: Replace github action with bash script
