canonical/bundle-kubeflow

README.md

Add instructions for deploying to CDK to the README. Also updates variable naming elsewhere to be consistent.

Add CDK instructions to README

---

storage/local-storage.yaml
storage/persistent-volume.yaml

Useful for CI and pointing users at a one-command way to set up local storage.

Add yaml convenience files

---

bundle.yaml

So that they're set up automatically

Add Ambassador relations to bundle.yaml

---

README.md

The fixes that we need have reached stable

Update README to use Juju stable

---

scripts/deploy-aws.sh
scripts/deploy-microk8s.sh

Since they're now set up for that.

Use promulgated bundle name in deploy scripts

---

scripts/deploy-aws.sh
scripts/deploy-microk8s.sh

Makes them work with Juju 2.6, and regularizes some drift between the two of them.

Update and regularize deploy scripts

---

bundle.yaml

Adds Seldon to Kubeflow + Redis dependency

Add Seldon to Kubeflow bundle

---

bundle.yaml

To make it look nice in the GUI by default

Add Juju GUI placement annotations

---

scripts/deploy-aws.sh
scripts/deploy-microk8s.sh

Fixes #19 
Adds fast-fail checking of dependencies with helpful error message, parameterizes variables to allow overriding, and removes some removal code that was only necessary for a bit because of living on the edge.

Improve deploy scripts

---

.travis.yml
bundle.yaml
charms/ambassador-auth/config.yaml
charms/ambassador-auth/icon.svg
charms/ambassador-auth/layer.yaml
charms/ambassador-auth/metadata.yaml
charms/ambassador-auth/reactive/ambassador_auth.py
charms/ambassador-auth/wheelhouse.txt
overlays/ci.yml
scripts/deploy-aws.sh
scripts/deploy-microk8s.sh
tests/session.py
tests/test_jupyterhub.py
tests/test_kubectl.py

Adding basic http auth so that there's at least some barrier to hackers spinning up a bunch of free servers.

Adding Ambassador HTTP Basic auth

---

.travis.yml
charms/ambassador-auth/reactive/ambassador_auth.py
charms/ambassador/reactive/ambassador.py
charms/argo-controller/reactive/argo_controller.py
charms/argo-ui/reactive/argo_ui.py
charms/jupyter-controller/reactive/jupyter_controller.py
charms/jupyter-web/reactive/jupyter_web.py
charms/jupyterhub/files/jupyterhub_config.py
charms/jupyterhub/reactive/jupyterhub.py
charms/mariadb-k8s/lib/charms/layer/mariadb_k8s.py
charms/mariadb-k8s/reactive/mariadb_k8s.py
charms/minio/reactive/minio.py
charms/pipelines-api/reactive/pipelines_api.py
charms/pipelines-dashboard/reactive/pipelines_dashboard.py
charms/pipelines-persistence/reactive/pipelines_persistence.py
charms/pipelines-scheduledworkflow/reactive/pipelines_scheduledworkflow.py
charms/pipelines-ui/reactive/pipelines_ui.py
charms/pipelines-viewer/reactive/pipelines_viewer.py
charms/pytorch-operator/reactive/pytorch_operator.py
charms/redis-k8s/reactive/redis.py
charms/seldon-api-frontend/reactive/seldon_api_frontend.py
charms/seldon-cluster-manager/reactive/seldon_cluster_manager.py
charms/tensorboard/reactive/tensorboard.py
charms/tf-job-dashboard/reactive/tf_job_dashboard.py
charms/tf-job-operator/reactive/tf_job_operator.py
charms/tf-serving/reactive/tf_serving.py
pyproject.toml
tests/session.py
tests/test_jupyterhub.py

Ensures that Python code is properly formatted in Travis CI

Format Python code with black

---

.travis.yml

See https://github.com/juju/charm-tools/issues/532

Remove git configuration for protocol v2

---

charms/seldon-cluster-manager/reactive/seldon_cluster_manager.py

To properly set up communication between pods in deployed containers.

Add SeldonIO env vars

---

bundle.yaml

Make charm arrangement in Juju gui look nicer

---

.travis.yml
scripts/deploy-microk8s

Skip enabling dashboard in CI, since it's unnecessary and causes problems.

Fix Travis build issues

---

bundle.yaml
charms/modeldb-backend/icon.svg
charms/modeldb-store/icon.svg
charms/modeldb-ui/icon.svg

Adds logo and moves to better grid locations

Update ModelDB charms

---

charms/ambassador-auth/reactive/ambassador_auth.py
charms/ambassador/reactive/ambassador.py
charms/katib-manager/config.yaml
charms/katib-manager/reactive/katib_manager.py
charms/katib-ui/reactive/katib_ui.py
charms/mariadb/reactive/mariadb.py
charms/minio/reactive/minio.py
charms/modeldb-ui/reactive/modeldb_ui.py
charms/pipelines-api/config.yaml
charms/pipelines-api/reactive/pipelines_api.py
charms/pipelines-persistence/reactive/pipelines_persistence.py
charms/redis/reactive/redis.py
charms/seldon-api-frontend/reactive/seldon_api_frontend.py
charms/seldon-cluster-manager/reactive/seldon_cluster_manager.py
overlays/ci.yml

Takes care of various bits of housework that need to get done, split up into commits

Delint and optimize code

---

charms/pipelines-api/files/sample_config.json
charms/pipelines-api/metadata.yaml
charms/pipelines-api/reactive/pipelines_api.py

Upstream pushed up a new docker image that now respects the mysql password getting set.

Update Pipelines API docker image

---

charms/ambassador-auth/reactive/ambassador_auth.py
charms/ambassador/reactive/ambassador.py
charms/jupyter-controller/reactive/jupyter_controller.py
charms/jupyter-web/reactive/jupyter_web.py
charms/jupyterhub/reactive/jupyterhub.py
charms/katib-controller/reactive/katib_controller.py
charms/katib-manager/config.yaml
charms/katib-manager/metadata.yaml
charms/katib-manager/reactive/katib_manager.py
charms/katib-ui/reactive/katib_ui.py
charms/mariadb/reactive/mariadb.py
charms/metacontroller/reactive/metacontroller.py
charms/minio/reactive/minio.py
charms/modeldb-backend/reactive/modeldb_backend.py
charms/modeldb-store/reactive/modeldb_store.py
charms/modeldb-ui/reactive/modeldb_ui.py
charms/pipelines-api/reactive/pipelines_api.py
charms/pipelines-dashboard/reactive/pipelines_dashboard.py
charms/pipelines-persistence/reactive/pipelines_persistence.py
charms/pipelines-scheduledworkflow/reactive/pipelines_scheduledworkflow.py
charms/pipelines-ui/reactive/pipelines_ui.py
charms/pipelines-viewer/reactive/pipelines_viewer.py
charms/pytorch-operator/reactive/pytorch_operator.py
charms/redis/reactive/redis.py
charms/seldon-api-frontend/reactive/seldon_api_frontend.py
charms/seldon-cluster-manager/reactive/seldon_cluster_manager.py
charms/tensorboard/reactive/tensorboard.py
charms/tf-job-dashboard/reactive/tf_job_dashboard.py
charms/tf-job-operator/reactive/tf_job_operator.py
charms/tf-serving/reactive/tf_serving.py

Takes care of a few cleanup items, split out by commit

Code cleanup

---

.travis.yml

It breaks too often and takes a very long time.

Remove bundle deploys to microk8s from Travis

---

tests/pipelines/cowsay.py
tests/test_pipelines.py

Adds a basic pipeline example and runs it with pytest to ensure that pipelines are working during CI testing.

Add basic pipeline example and run with pytest

---

scripts/manage-cdk

Pass model arg into call to info

---

tests/pipelines/mnist.py

Jenkins is getting a 1-tuple instead of a 2-tuple

Fix string formatting issue in print statement

---

charms/argo-controller/config.yaml

Correct Argo config option type

---

tests/dump-pipeline-logs.sh

Adds a bash script that dumps out logs for each completed pipeline container.

Better pipeline dog dumping for CI

---

bundle.yaml
charms/pipelines-persistence/metadata.yaml
charms/pipelines-scheduledworkflow/metadata.yaml
charms/pipelines-ui/metadata.yaml
charms/pipelines-ui/reactive/pipelines_ui.py

The newer images allow overriding the minio service endpoint in the UI.

Update pipeline docker images

---

README.md

Fixes #101. Adds updated microk8s setup instructions.

Add microk8s group instructions to README

---

charms/ambassador-auth/reactive/ambassador_auth.py
charms/katib-manager/reactive/katib_manager.py
charms/mariadb/reactive/mariadb.py
charms/metacontroller/reactive/metacontroller.py
charms/minio/reactive/minio.py
charms/modeldb-store/reactive/modeldb_store.py
charms/modeldb-ui/reactive/modeldb_ui.py
charms/pipelines-api/reactive/pipelines_api.py
charms/pipelines-dashboard/reactive/pipelines_dashboard.py
charms/pipelines-ui/reactive/pipelines_ui.py
charms/pipelines-viewer/reactive/pipelines_viewer.py
charms/pytorch-operator/reactive/pytorch_operator.py
charms/redis/reactive/redis.py
charms/seldon-api-frontend/reactive/seldon_api_frontend.py
charms/seldon-cluster-manager/reactive/seldon_cluster_manager.py
charms/tensorboard/reactive/tensorboard.py
charms/tf-job-dashboard/reactive/tf_job_dashboard.py
charms/tf-job-operator/reactive/tf_job_operator.py
charms/tf-serving/reactive/tf_serving.py

The semantics we wanted were OR, but @when has AND semantics.
Fixes #111

Convert usages of multiple flag @when to @when_any

---

overlays/cdk.yml

Stable 1.16 has working GPU support

Remove hardcoded 1.15 channel for kubernetes charms

---

charms/jupyter-controller/reactive/jupyter_controller.py

Fixes #118, by creating service account.

Add jupyter-notebook service account creation

---

charms/pipelines-api/reactive/pipelines_api.py

kubernetesResources key was missing.

Fix pipeline-runner service account creation

---

charms/ambassador-auth/reactive/ambassador_auth.py
charms/ambassador/reactive/ambassador.py
charms/argo-controller/reactive/argo_controller.py
charms/argo-ui/reactive/argo_ui.py
charms/jupyter-controller/reactive/jupyter_controller.py
charms/jupyter-web/reactive/jupyter_web.py
charms/katib-controller/reactive/katib_controller.py
charms/katib-manager/reactive/katib_manager.py
charms/katib-ui/reactive/katib_ui.py
charms/metacontroller/reactive/metacontroller.py
charms/minio/reactive/minio.py
charms/modeldb-backend/reactive/modeldb_backend.py
charms/modeldb-store/reactive/modeldb_store.py
charms/modeldb-ui/reactive/modeldb_ui.py
charms/pipelines-api/reactive/pipelines_api.py
charms/pipelines-dashboard/reactive/pipelines_dashboard.py
charms/pipelines-persistence/reactive/pipelines_persistence.py
charms/pipelines-scheduledworkflow/reactive/pipelines_scheduledworkflow.py
charms/pipelines-ui/reactive/pipelines_ui.py
charms/pipelines-viewer/reactive/pipelines_viewer.py
charms/pytorch-operator/reactive/pytorch_operator.py
charms/redis/reactive/redis.py
charms/seldon-api-frontend/reactive/seldon_api_frontend.py
charms/seldon-cluster-manager/reactive/seldon_cluster_manager.py
charms/tensorboard/reactive/tensorboard.py
charms/tf-job-dashboard/reactive/tf_job_dashboard.py
charms/tf-job-operator/reactive/tf_job_operator.py
charms/tf-serving/reactive/tf_serving.py

Add a handler for the upgrade-charm hook

Enable charm upgrading

---

scripts/cli.py

If a deployment doesn't have kubernetes-worker/0 for whatever reason, we need to still calculate a public IP based on one of the other workers. Still prefer the first unit, sorted by name, so that repeated runs are stable.
Fixes #135

Remove hardcoded worker unit reference

---

charms/jupyter-controller/reactive/jupyter_controller.py
charms/jupyter-web/reactive/jupyter_web.py

The frontend had no permissions, and the controller had only local permissions.

Fix Jupyter permissions

---

charms/argo-ui/reactive/argo_ui.py

It wants to be able to view cluster-wide resources.

Create ClusterRole for Argo UI

---

README.md
charms/pipelines-api/files/condition.yaml
charms/pipelines-api/files/exit_handler.yaml
charms/pipelines-api/files/parallel_join.yaml
charms/pipelines-api/files/sample_config.json
charms/pipelines-api/files/sequential.yaml
charms/pipelines-api/files/xgboost_training_cm.yaml
charms/pipelines-api/reactive/pipelines_api.py
pipeline-samples/README.md
pipeline-samples/condition.py
pipeline-samples/exit_handler.py
pipeline-samples/parallel_join.py
pipeline-samples/sequential.py
pipeline-samples/xgboost_training_cm.py
pyproject.toml

Adds sample pipelines that work with containerd, which is used by both MicroK8s and Charmed Kubernetes.
Fixes #122

Add pipeline samples

---

scripts/cli.py

Since Ambassador isn't set up for HTTPS itself, we need to go through the process of creating an Ingress with TLS enabled, then connecting via localhost.

Support https in microk8s deployments

---

charms/ambassador/reactive/ambassador.py
charms/argo-ui/reactive/argo_ui.py
charms/pipelines-viewer/reactive/pipelines_viewer.py
charms/tf-job-dashboard/reactive/tf_job_dashboard.py
charms/tf-job-operator/reactive/tf_job_operator.py

Juju now does some stricter YAML checking, and we had some debris

Fix invalid YAML passed to pod spec set

---

bundle.yaml

To make it a little bit lighter on resources by default

Remove non-essential services from bundle

---

bundle.yaml

Those applications have now been removed

Remove invalid relations in bundle

---

scripts/cli.py

Print stderr when listing clouds fails

---

tests/pipelines/mnist.py

Remove wrapper script in MNIST pipeline

---

README.md

Add README note about minimum recommended memory

---

charms/dex-auth/reactive/dex_auth.py

The service wasn't getting restarted when the config file changed, this forces Kubernetes to see the Deployment as different.

Update dex-auth pod spec when configmap changes

---

CODEOWNERS

Updates CODEOWNERS file based on who can actually give reviews

Update CODEOWNERS file with current reviewers

---

charms/cert-manager-webhook/reactive/webhook.py

Use correct hookenv function

---

.github/workflows/test-microk8s.yaml

Spins up an AWS instance where microk8s is installed, kubeflow deployed, and then tested.

Test Kubeflow in Github actions

---

.github/workflows/test-microk8s.yaml

Due to https://bugs.launchpad.net/juju/+bug/1881769

Use juju 2.7 in CI

---

charms/pipelines-api/reactive/pipelines_api.py

If the relation doesn't exist yet, we'll get an IndexError

Better handling of relation data in pipelines-api

---

.github/workflows/test-microk8s.yaml
bundle-edge.yaml
bundle-lite.yaml
charms/pipelines-api/reactive/pipelines_api.py
pytest.ini
scripts/cli.py
tests/test_kubectl.py
tests/test_pipelines.py

Adds lite and edge bundles, and updates CI testing to include them

Add lite and edge bundles

---

.github/workflows/publish-bundle.yaml
bundle-edge.yaml

Deploys these bundles the charm store along with the full bundle

Add deployment of lite and edge bundles

---

charms/ambassador/reactive/ambassador.py
charms/argo-controller/reactive/argo_controller.py
charms/argo-ui/reactive/argo_ui.py
charms/dex-auth/reactive/dex_auth.py
charms/jupyter-controller/reactive/jupyter_controller.py
charms/jupyter-web/reactive/jupyter_web.py
charms/katib-controller/reactive/katib_controller.py
charms/katib-manager/reactive/katib_manager.py
charms/katib-ui/reactive/katib_ui.py
charms/kubeflow-dashboard/reactive/kubeflow_dashboard.py
charms/kubeflow-profiles/reactive/kubeflow_profiles.py
charms/metacontroller/reactive/metacontroller.py
charms/metadata-api/reactive/metadata_api.py
charms/metadata-envoy/reactive/metadata_envoy.py
charms/metadata-grpc/reactive/metadata_grpc.py
charms/metadata-ui/reactive/metadata_ui.py
charms/minio/reactive/minio.py
charms/oidc-gatekeeper/reactive/oidc_auth.py
charms/pipelines-api/reactive/pipelines_api.py
charms/pipelines-persistence/reactive/pipelines_persistence.py
charms/pipelines-scheduledworkflow/reactive/pipelines_scheduledworkflow.py
charms/pipelines-ui/reactive/pipelines_ui.py
charms/pipelines-viewer/reactive/pipelines_viewer.py
charms/pipelines-visualization/reactive/pipelines_visualization.py
charms/pytorch-operator/reactive/pytorch_operator.py
charms/seldon-core/reactive/seldon_core.py
charms/tensorboard/reactive/tensorboard.py
charms/tf-job-operator/reactive/tf_job_operator.py
scripts/cli.py

Copies this check to all charms, and changes it to a logging statement instead of blocking the charm, as blocking the charm will cause juju wait to fail.

Check leadership before calling pod spec set

---

scripts/cli.py

Checks that required commands exist in cli.py scripts before doing any actual work, and tell the user how to install them if not.
Fixes #228

Check that commands exist in cli.py

---

charms/katib-controller/reactive/katib_controller.py

Fixes error message from new Go releases that break cert handling with this message:
x509: certificate relies on legacy Common Name field, use SANs ...

Switch Katib cert to use SANs

---

.github/workflows/test-microk8s.yaml
charms/dex-auth/reactive/dex_auth.py
charms/katib-controller/metadata.yaml
charms/katib-controller/reactive/katib_controller.py
charms/oidc-gatekeeper/reactive/oidc_auth.py
charms/pipelines-api/metadata.yaml
charms/pipelines-api/reactive/pipelines_api.py
charms/seldon-core/reactive/seldon_core.py
scripts/cli.py
tests/dump-stdout.sh
tests/test_kubectl.py

Fixes issue with mariadb charms not deploying properly with Juju 2.8, and adds Juju 2.8 to the CI testing

Fix bundle for Juju 2.8 and test 2.8 in CI

---

charms/argo-controller/config.yaml
charms/argo-controller/layer.yaml
charms/argo-controller/metadata.yaml
charms/argo-controller/reactive/argo_controller.py
charms/minio/config.yaml
charms/minio/layer.yaml
charms/minio/metadata.yaml
charms/minio/reactive/minio.py
charms/oidc-gatekeeper/reactive/oidc_auth.py
charms/pipelines-api/config.yaml
charms/pipelines-api/layer.yaml
charms/pipelines-api/metadata.yaml
charms/pipelines-api/reactive/pipelines_api.py
charms/pipelines-ui/layer.yaml
charms/pipelines-ui/metadata.yaml
charms/pipelines-ui/reactive/pipelines_ui.py
scripts/cli.py

Removes the need for an overlay for specifying passwords that a user shouldn't need to concern themselves with.

Fix password handling in charms

---

charms/katib-controller/reactive/katib_controller.py

Change `juju.io/disable-name-prefix` to `model.juju.is/disable-prefix`;

Change juju.io/disable-name-prefix to model.juju.is/disable-prefix;

---

charms/seldon-core/config.yaml
charms/seldon-core/layer.yaml
charms/seldon-core/metadata.yaml
charms/seldon-core/reactive/seldon_core.py

The new relation is optional, and will set ISTIO_ENABLED accordingly.

Add service-mesh relation to seldon-core

---

tests/pipelines/katib.py
tests/test_pipelines.py

Upstream master no longer has v1alpha3 after PR #1396

Specify git revision in katib test example

---

charms/argo-controller/README.md

Update argo docs link

---

bundle-edge.yaml
bundle-lite.yaml
bundle.yaml

Updating the rest of the charm syntax in bundles

---

scripts/cli.py

Specifying model in CK setup script

---

.github/workflows/test-microk8s.yaml
bundle-lite.yaml
bundle.yaml
charms/jupyter-controller/files/crds.yaml
charms/jupyter-controller/layer.yaml
charms/jupyter-controller/metadata.yaml
charms/jupyter-controller/reactive/jupyter_controller.py
charms/jupyter-web/files/spawner_ui_config.yaml
charms/jupyter-web/layer.yaml
charms/jupyter-web/metadata.yaml
charms/jupyter-web/reactive/jupyter_web.py
scripts/cli.py
tests/test_selenium.py

Also adds functional UI testing to ensure we don't get dashboard regressions

Update Jupyter charms to latest upstream version 

---

.github/workflows/test-microk8s.yaml
charms/jupyter-controller/reactive/jupyter_controller.py
conftest.py
tests/test_selenium.py

Also fix jupyter-controller env var name, since it's breaking deletion

Add more Jupyter testing

---

.github/workflows/test-microk8s.yaml
README.md
requirements.txt
test-requirements.txt
tests/test_kubectl.py
tests/test_selenium.py

Clean up tests and add documentation for running them

---

.github/workflows/publish-bundle.yaml

Now that admission-webhook is using it

Add charmcraft snap to publishing job

---

charms/katib-controller/reactive/katib_controller.py
charms/katib-ui/reactive/katib_ui.py

This is required for katib working correctly on AKS.

Change katib roles to clusterroles

---

pytest.ini
tests/Dockerfile.object_detection
tests/pipelines/common.py
tests/pipelines/object_detection.py
tests/test_pipelines.py

Adds pipeline test that continues training a pretrained pet detector model, then tests serving it.

Add Object Detection pipeline example

---

tests/test_kubectl.py

Ignore modeloperator service account for SA tests;

Ignore modeloperator service account for SA tests;

---

.github/workflows/test-microk8s.yaml

Adds restarting of microk8s to CI process, to ensure that it's handled well.

Ensure that microk8s restarts are handled

---

README.md
tests/README.md

Moved to tests/README.md, as it's not relevant to casual README readers

Move testing information

---

bundle-edge.yaml
bundle-lite.yaml
bundle.yaml

Since there isn't a way to keep them updated anymore, with the GUI having removed drag-and-drop functionality.

Remove GUI layout from bundles

---

.github/workflows/test-aks.yaml

This action will deploy a AKS on Azure, Bootstrap
a Juju Controller, Deploy Kubeflow and run the test
suite.
Once it finishes it will tear down everything.
It will run weekly at 23.00 on Wednesday.

Add AKS Test Action

---

bundle-lite.yaml
bundle.yaml
scripts/cli.py
tests/README.md
tests/test_selenium.py

Switch to nip.io in selenium tests.
Upgrade Dex-auth in bundles.
Also point to charmstore in cli.py.

Fix Selenium and update Dex

---

bundle-lite.yaml
bundle.yaml

This fixes the following 2 bugs:
https://bugs.launchpad.net/kubeflow-bundle/+bug/1929248
https://github.com/canonical/bundle-kubeflow/issues/354

Update OIDC Gatekeeper and KFP UI

---

.github/workflows/integrate.yaml
bundle-lite.yaml
bundle.yaml
test-requirements.txt
tests/test_pipelines.py
tests/test_selenium.py

Includes Jupyter UI rewrite
Fixes https://github.com/canonical/notebook-operators/issues/10

Update Jupyter charms

---

.github/workflows/integrate.yaml
.github/workflows/test-aks.yaml
ops_tests/test_upgrade_charm.py
test-requirements.txt
tox.ini

Add upgrade test which deploys full bundle in stable channel and tries to upgrade to the bundle in edge.
This test is executed with pytest operator and tox.
Also change github actions to use charmcraft snap instead of pip package.

Upgrade Test

---

releases/1.6/beta/kubeflow/bundle.yaml
releases/1.6/edge/kubeflow/bundle.yaml

Please note this PR depends on the changes that [PR#112](https://github.com/canonical/istio-operators/pull/112) introduces, and thus should not be merged before that one.

refactor: rename gateway relation to gateway-info

---

.github/workflows/integrate.yaml
.github/workflows/publish.yaml
.github/workflows/test-aks.yaml

[skip ci] git-xargs programmatic commit

ci: Replace ubuntu-latest with ubuntu-20.04

---

releases/1.7/beta/kubeflow/bundle.yaml
releases/1.7/edge/kubeflow/bundle.yaml

fix: typo in 1.7 bundle for knative eventing

---

releases/1.7/beta/kubeflow/bundle.yaml
releases/1.7/edge/kubeflow/bundle.yaml
releases/latest/edge/bundle.yaml

Upgrade to match most recent versions.

feat: update 1.7/beta/edge and latest/edge bundles

---

releases/1.7/stable/kubeflow/README.md
releases/1.7/stable/kubeflow/bundle.yaml
releases/1.7/stable/kubeflow/charmcraft.yaml

This PR defines the 1.7/stable bundle definition.

feat: add 1.7/stable bundle definition

---

releases/latest/edge/bundle.yaml

- Updated bundle with mysql-k8s charm.
- Updated relations.

feat: mysql integration

---

releases/latest/edge/bundle.yaml

- Added trust to new sidecar charns.

fix: added trust

---

docs/upgrade-guide-1.6-to-1.7.ipynb
docs/upgrade-guide-1.6-to-1.7.md

Removed data loss warning from the notebook and re-generated the associated `.md`.

Kf 3588 remove data loss warning

---

tests-bundle/README.md

Added readme to full bundle tests

full bundle tests README

---

releases/1.4/edge/kubeflow/bundle.yaml
releases/1.4/stable/kubeflow/bundle.yaml
releases/1.6/beta/kubeflow/bundle.yaml
releases/1.6/edge/kubeflow/bundle.yaml
releases/1.6/stable/kubeflow/bundle.yaml
releases/1.7/beta/kubeflow/bundle.yaml
releases/1.7/edge/kubeflow/bundle.yaml
releases/1.7/stable/kubeflow/bundle.yaml
releases/latest/beta/bundle.yaml
releases/latest/edge/bundle.yaml

Included 1.4 and 1.6 as upgrade content touches these versions
kubeflow lite not included

Added docs links

---

releases/latest/edge/bundle.yaml

Run kserve-controller in serverless mode in latest/edge

Run kserve-controller in serverless mode in latest/edge

---

releases/1.8/beta/README.md
releases/1.8/beta/bundle.yaml
releases/1.8/beta/charmcraft.yaml

releases: Create 1.8/beta bundle

---

releases/1.8/beta/bundle.yaml

* set kfp-operators charms to `latest/edge`
* set argo-controller charm to `latest/edge`

Fix: update 1.8 beta bundle definition

---

releases/latest/beta/bundle.yaml

Updates the `latest/beta` bundle definition due to changes made in `1.8/beta`

feat: update latest/beta based on 1.8/beta

---

releases/1.8/stable/kubeflow/README.md
releases/1.8/stable/kubeflow/bundle.yaml
releases/1.8/stable/kubeflow/charmcraft.yaml

Copy over the beta bundle but change all risks to use stable instead.

Add 1.8 stable bundle

---

.github/ISSUE_TEMPLATE/task.yaml

Update the task template to expose context and definition of done.

Update task template

---

.github/workflows/deploy-to-aks.yaml
.github/workflows/full-bundle-tests.yaml

Part of canonical/bundle-kubeflow#859
Part of canonical/bundle-kubeflow#862

ci: bump juju 3.1 -> 3.5

---

scripts/airgapped/deploy-1.8.sh
tests/airgapped/airgap.sh

adds the missing images from https://github.com/canonical/knative-operators/issues/183 and https://github.com/canonical/knative-operators/issues/185

fix: add missing images to airgap deployment script

---

releases/1.9/edge/README.md
releases/1.9/edge/bundle.yaml
releases/1.9/edge/charmcraft.yaml
releases/1.9/stable/README.md
releases/1.9/stable/bundle.yaml
releases/1.9/stable/charmcraft.yaml

Adds edge and stable bundle definitions for CKF 1.9.

feat: add 1.9 bundle definitions

---

charmcraft.yaml

Reverts canonical/bundle-kubeflow#1071

Revert "Add Charmhub home page link to charmcraft.yaml"

---

releases/1.9/edge/bundle.yaml
releases/1.9/stable/bundle.yaml

chore: update 1.9 bundle definitions to use kfp 2.3

---

.github/dependencies.yaml
.github/workflows/full-bundle-tests.yaml
test-reference/versions.json

Ref canonical/bundle-kubeflow#1157

chore(ci): bump microk8s to 1.31

---

.github/cluster.yaml
.github/dependencies.yaml
.github/workflows/deploy-to-aks.yaml
.github/workflows/deploy-to-eks.yaml
.github/workflows/full-bundle-tests.yaml

I have just started to apply the changes to one of the relevant workflows (EKS) and if they are sane, I can roll them out to all the workflows

feat: Add bundle url as input and use latest as default

---

.github/workflows/deploy-to-aks.yaml
.github/workflows/deploy-to-eks.yaml

Close #1235
Ref canonical/kubeflow-ci#152

fix(ci): update logs action

---

releases/1.10/candidate/README.md
releases/1.10/candidate/bundle.yaml
releases/1.10/candidate/charmcraft.yaml

Add 1.10/candidate bundle in order to enable its testing.

feat: Add 1.10/candidate bundle

---

releases/1.10/stable/README.md
releases/1.10/stable/bundle.yaml
releases/1.10/stable/charmcraft.yaml

Add 1.10/stable bundle.
Close https://warthogs.atlassian.net/browse/KF-7171

feat: Add `1.10/stable` bundle

---

releases/1.10/stable/bundle.yaml

Update `_github_repo_branch` in the bundle.yaml file.

fix(1.10/stable): update `_github_repo_branch`
